/**
 * Generates public/sitemap.xml from src/config/seo.js at build time.
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PAGE_SEO, SITE, LOCATION_SITEMAP_ENTRIES } from '../src/config/seo.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../public/sitemap.xml');
const lastmod = new Date().toISOString().split('T')[0];

/** @param {string} path @param {number} priority @param {string} changefreq */
function urlEntry(path, priority, changefreq) {
  const loc = `${SITE.url}${path}`;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority.toFixed(1)}</priority>
  </url>`;
}

const pageEntries = Object.values(PAGE_SEO).map((page) =>
  urlEntry(page.path, page.priority, page.changefreq),
);

const locationEntries = LOCATION_SITEMAP_ENTRIES.map((entry) =>
  urlEntry(entry.path, entry.priority, entry.changefreq),
);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by scripts/generate-sitemap.mjs — do not edit manually -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...pageEntries, ...locationEntries].join('\n')}
</urlset>
`;

writeFileSync(outPath, xml, 'utf8');
console.log(`Wrote ${pageEntries.length + locationEntries.length} URLs to public/sitemap.xml`);
